### ISSUE TITLE
Allow accepting and rejecting suggestions

### ISSUE THREAD

**Issue by Atrate** [GoodClover/OSM-Discord-bot#2]
If OSM-Discord-bot is going to replace Dyno's custom commands, it would be nice if it supported accepting and rejecting the posted [suggestions](https://github.com/GoodClover/OSM-Discord-bot/blob/a68e2115674f99828e6c705478365c6479af9a41/main.py#L441) in the form of a moderator-only command that could refer to the suggestion's (TBI) ID.

This would either append to the original message or create a reply with a message like "Suggestion X has been accepted/rejected".

**Comment by GoodClover** [comment]
If the mods want this I can have a go at doing it :)
I think making it add to the original message would be best, in order to avoid clutter.

Note my original aim wasn't to completely replace Dyno's commands - just the `googlebad` and `josmtip` ones.

What do you mean by "(TBI) ID"?
Discord message ID would probably be easiest: <kbd>right-click</kbd> → <kbd>"Copy ID"</kbd> (with developer mode on)

**Comment by Atrate** [comment]
> What do you mean by "(TBI) ID"?

I completely forgot that Discord has internal message IDs and assumed some kind of suggestion ID had To Be Implemented. Using Discord IDs simplifies things.

**Comment by GoodClover** [comment]
Done in 2a7abbdc2483a955fda5b9d4b2953a4c3fcbc699
